name: Lane Design Group grid beta test
favicon: null
layout_spectrum: 0
typography_spectrum: 0.9994
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3261137220542878
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
